CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password VARCHAR(60) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    role VARCHAR(10) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_email_normalized CHECK (
        email = lower(btrim(email)) AND length(email) > 0
    ),
    CONSTRAINT ck_users_first_name_not_blank CHECK (length(btrim(first_name)) > 0),
    CONSTRAINT ck_users_last_name_not_blank CHECK (length(btrim(last_name)) > 0),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

COMMENT ON COLUMN users.password IS 'BCrypt hash only; never a plaintext password';
