CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    capacity INTEGER NOT NULL,
    description VARCHAR(2000),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_rooms_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_rooms_capacity_positive CHECK (capacity > 0)
);

-- Active room catalog with default ordering by name, id.
CREATE INDEX idx_rooms_active_name_id ON rooms (name, id) WHERE active = TRUE;
