CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE RESTRICT,
    CONSTRAINT ck_bookings_time_order CHECK (end_time > start_time),
    CONSTRAINT ck_bookings_finite_times CHECK (isfinite(start_time) AND isfinite(end_time)),
    CONSTRAINT ck_bookings_status CHECK (status IN ('ACTIVE', 'CANCELLED'))
);

-- /api/bookings/my with default ordering.
CREATE INDEX idx_bookings_user_start_id ON bookings (user_id, start_time DESC, id DESC);
-- /api/admin/bookings with default ordering.
CREATE INDEX idx_bookings_start_id ON bookings (start_time DESC, id DESC);
-- Room history and foreign-key lookups, including cancelled bookings.
CREATE INDEX idx_bookings_room_start ON bookings (room_id, start_time);
